name: img-processing

on:
  push:
    branches:
      - master
      - release/**
    paths:
      - '**.svg'
      - 'package.json'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Convert to PNG
      run: mogrify -format png -resize 200 -background none kaskadi-logo.svg
    - name: Upload binary to S3 bucket
      uses: kaskadi/action-s3cp@master
      env:
        AWS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_KEY_SECRET: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
