name: img-processing

on:
  push:
    paths:
      - '**.svg'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Convert to PNG
      run: mogrify -format png -resize 200 -background none kaskadi-logo.svg
    - name: Upload binary to S3 bucket
    uses: tpaschalis/s3-sync-action@master
    with:
      args: --acl public-read
    env:
      FILE: ./kaskadi-logo.png
      AWS_REGION: 'eu-central-1'
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
